### ISSUE TITLE
installing via pip uses old version

### ISSUE THREAD

**Issue by mrkrause** [Aifred-Health/Vulcan#116]
Running pip install vulcanai seems to request the old version. 

For me, the build fails looking for lasagne>=0.2.dev1, which we obviously don't need for pytorch. 

I think the directions for installing via a cloned repo are wrong too: 
(irl_grey_mk) mkrause@ml:~/Vulcan$ pip install -e vulcanai
Directory 'vulcanai' is not installable. File 'setup.py' not found.

I think you either want to do pip install -e . (where setup.py is) or run the command from one directory up.

**Comment by rfratila** [comment]
It has been updated in PR #127
