### ISSUE TITLE
Speed up GPU <--> CPU data transfers, only do when necessary

### ISSUE THREAD

**Issue by nirtiac** [Aifred-Health/Vulcan#140]
Made this issue so that I could list out all the potential improvements I've found while researching this topic. May be helpful for others in the future. 

- use from_numpy() to avoid creating a copy when copying an array https://pytorch.org/docs/stable/torch.html#torch.from_numpy, also see warnings here https://pytorch.org/docs/stable/torch.html 
- use pin_memory for CPU-GPU for speedup http://deeplearnphysics.org/Blog/2018-10-02-Pinning-data-to-GPU.html 
- non_blocking=False allows you to overlap CPU and GPU computations https://discuss.pytorch.org/t/why-set-cuda-non-blocking-false-for-target-variables/16943 
- use map_location() for more efficient saving (need to investigate more) https://discuss.pytorch.org/t/on-a-cpu-device-how-to-load-checkpoint-saved-on-gpu-device/349 
- use https://discuss.pytorch.org/t/what-does-torch-backends-cudnn-benchmark-do/5936 for a speedup if input sizes do not vary. see here too https://discuss.pytorch.org/t/solved-make-sure-that-pytorch-using-gpu-to-compute/4870/7 

Issues I've found in our code:
- setting device when not needed. STATUS: this doesn't matter. 
- torch.tensor always creates a copy of the data STATUS: not used mostly everywhere except for TensorDataset and other preprocessing, to be fixed 
- we convert multiple times in several functions, unnecessarily, including forward_pass. STATUS: fixed
- we may be loading data all at once STATUS: not true, but tensordataset
- obviously, we're not efficiently using all of our GPUs, could be using DataParallel, but difficult. STATUS: not fixed, leaving for now, also we don't really need them yet.

**Comment by rfratila** [comment]
There’s this post on the Pytorch forums about GPU usage that might help explain some behind the scenes topics. https://discuss.pytorch.org/t/how-to-prefetch-data-when-processing-with-gpu/548/17

**Comment by nirtiac** [comment]
Hm interesting, thanks Rob. I've added it to the future resources folder for when we integrate DataParallel.

**Comment by nirtiac** [comment]
Closed in #163
