### ISSUE TITLE
epoch count not correct with cross validate after fit

### ISSUE THREAD

**Issue by nirtiac** [Aifred-Health/Vulcan#154]

**Comment by rfratila** [comment]
@nirtiac does the internal epoch state not get updated/preserved appropriately after a cross validate? might be the passed reference and determining exactly which copy get's trained and where those back references lie.

**Comment by nirtiac** [comment]
actually @rfratila it seems to be fine, it was stemming from confusing over using cross validate in a notebook - the output gets rather messy. I've tagged Sneha to see if she can deal with that issue.
