### ISSUE TITLE
consolidate criterion_spec and criterion so there's no duplication

### ISSUE THREAD

**Issue by rfratila** [Aifred-Health/Vulcan#30]
Also if we define the Modules within a `dict` it will be protected. Meaning it won't be added to the graph behind the scenes, unless it is explicitly defined/assigned. If we want to keep criter_spec we can make it to expect dict type input, something like: `criter_spec = {'main': nn.MSELoss()}`

**Comment by nirtiac** [comment]
Also remove unnecessary use of instance variables (self.whatever)

**Comment by nirtiac** [comment]
No longer relevant to our design, although improvements still need to be made to criter_spec
